apiVersion: topologies.eda.nokia.com/v1alpha1
kind: NetworkTopology
metadata:
  name: networktopology-test-1
  namespace: eda
spec:
  operation: create
  nodeTemplates:
    - labels:
        eda.nokia.com/role: leaf
        eda.nokia.com/security-profile: managed
      name: leaf
      nodeProfile: srlinux-ghcr-25.10.1
      platform: 7220 IXR-D3L
    - labels:
        eda.nokia.com/role: spine
        eda.nokia.com/security-profile: managed
      name: spine
      nodeProfile: srlinux-ghcr-25.10.1
      platform: 7220 IXR-D5
  nodes:
    - name: leaf1
      onBoarded: false
      template: leaf
    - name: leaf2
      onBoarded: false
      template: leaf
    - name: spine1
      onBoarded: false
      template: spine
  linkTemplates:
    - encapType: 'null'
      labels:
        eda.nokia.com/role: interSwitch
      name: isl
      speed: 25G
      type: interSwitch
    - encapType: dot1q
      labels:
        eda.nokia.com/role: edge
      name: edge
      type: edge
  links:
    - endpoints:
        - local:
            interface: ethernet-1-1
            node: leaf1
          remote:
            interface: ethernet-1-1
            node: spine1
      name: leaf1-spine1-1
      template: isl
    - endpoints:
        - local:
            interface: ethernet-1-2
            node: leaf1
          remote:
            interface: ethernet-1-2
            node: spine1
      name: leaf1-spine1-2
      template: isl
    - endpoints:
        - local:
            interface: ethernet-1-1
            node: leaf2
          remote:
            interface: ethernet-1-3
            node: spine1
      name: leaf2-spine1-1
      template: isl
    - endpoints:
        - local:
            interface: ethernet-1-2
            node: leaf2
          remote:
            interface: ethernet-1-4
            node: spine1
      name: leaf2-spine1-2
      template: isl
    - endpoints:
        - local:
            interface: ethernet-1-3
            node: leaf1
      name: leaf1-ethernet-1-3
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-4
            node: leaf1
      name: leaf1-ethernet-1-4
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-5
            node: leaf1
      name: leaf1-ethernet-1-5
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-6
            node: leaf1
      name: leaf1-ethernet-1-6
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-7
            node: leaf1
      name: leaf1-ethernet-1-7
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-8
            node: leaf1
      name: leaf1-ethernet-1-8
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-9
            node: leaf1
      name: leaf1-ethernet-1-9
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-10
            node: leaf1
        - local:
            interface: ethernet-1-11
            node: leaf1
      name: leaf1-e1011
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-3
            node: leaf2
      name: leaf2-ethernet-1-3
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-4
            node: leaf2
      name: leaf2-ethernet-1-4
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-5
            node: leaf2
      name: leaf2-ethernet-1-5
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-6
            node: leaf2
      name: leaf2-ethernet-1-6
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-7
            node: leaf2
      name: leaf2-ethernet-1-7
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-8
            node: leaf2
      name: leaf2-ethernet-1-8
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-9
            node: leaf2
      name: leaf2-ethernet-1-9
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-10
            node: leaf2
        - local:
            interface: ethernet-1-11
            node: leaf2
      name: leaf2-e1011
      template: edge
    - endpoints:
        - local:
            interface: ethernet-1-12
            node: leaf1
        - local:
            interface: ethernet-1-12
            node: leaf2
      name: leaf1-2-e1212
      template: edge
  checks:
    dryRun: true
  simulation:
    simNodeTemplates:
      - name: default
        type: TestMan
    simNodes:
      - name: testman-default
        template: default
    topology:
      - interface: '*'
        node: '*'
        simNode: testman-default
